import {
  Geist,
  Open_Sans,
  Poppins,
  Patrick_Hand,
  Nunito,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/AllComponents/navbar/Navbar";
import Footer from "@/components/AllComponents/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});
const openSans = Open_Sans({
  variable: "--font-open-sans",
  weight: "400",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  weight: "400",
  subsets: ["latin"],
});
const nunito = Nunito({
  variable: "--font-nunito",
  weight: "400",
  subsets: ["latin"],
});
const patrickHand = Patrick_Hand({
  variable: "--font-patrick-hand",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Innovate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${nunito.variable} ${openSans.variable} ${poppins.variable} ${patrickHand.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
